### ISSUE TITLE
Audiobench requires shared library libtinfo.so

### ISSUE THREAD

**Issue by rockerBOO** [joshua-maros/audiobench#14]
```
➜ ./Audiobench.bin
./Audiobench.bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

```
Which library is this requiring? I'm on Arch but any hint I can probably figure out which one.

**Comment by joshua-maros** [comment]
According to [this issue](https://github.com/jeaye/color_coded/issues/169#issuecomment-389929115), it looks like you need to install `ncurses5-compat-libs`.

**Comment by rockerBOO** [comment]
I don't think `ncurses5-compact-libs` is available anymore. I currently have `libtinfo.so.6` though which links to ncurses.

```
libtinfo.so.6 -> libncursesw.so.6
```

**Comment by joshua-maros** [comment]
I should investigate removing this dependency entirely, I think the code that requires it is detecting the width of the terminal window, but this code is never actually used. It was added in because a portion of the code was originally developed as a standalone command-line utility.
