### ISSUE TITLE
Website: after downloading one version, there is no way back to download another

### ISSUE THREAD

**Issue by henning** [joshua-maros/audiobench#20]
A minor confusion with the website:

When I want to download, I can chose my OS, then I can chose standalone or VST, and download.
Now I actualy want to download both, vst and standalone.

But there is no way back from the page saying "Thank you for checking out Audiobench! Your download will start shortly." - back buttons dont work, and it doesnt redirect me to where I came from. 

It takes a while until i realize I must reload the page so the JavaScript that makes this dialog is reset.

Not super important, but confusing.

**Comment by joshua-maros** [comment]
The newest version is packaged as one installer per OS, so in a very roundabout way, the problem has been solved lol.
