### ISSUE TITLE
Jack support in Linux (standalone)

### ISSUE THREAD

**Issue by tank-trax** [joshua-maros/audiobench#21]
I was wondering if you could add JACK support for Linux builds for the standalone 

in `audiobench/components/juce_frontend/CMakeLists.txt`

adding the two lines 

``` 
JUCE_ALSA=1
JUCE_JACK=1
```
to `target_compile_definitions` 

for example:

```
target_compile_definitions(
    Audiobench 
    PUBLIC
    JUCE_WEB_BROWSER=0  
    JUCE_USE_CURL=0     
    JUCE_VST3_CAN_REPLACE_VST2=0
    JUCE_ALSA=1
    JUCE_JACK=1
)
```
will accomplish this

**Comment by tank-trax** [comment]
I also noticed that the VST3 in Linux does not have MIDI in or out but it does have two Audio in and out

**Comment by joshua-maros** [comment]
Thanks for the research, I will add those in.

As far as the problems with MIDI in VST3, I have fixed this in a development version. However, the code base is currently in the middle of a number of changes to help make everything more stable and flexible. Hopefully I'll finish within a month or so and release a new version, which will work properly as a VST.

**Comment by tank-trax** [comment]
the most recent Audiobench.bin fix with the dependency links still only has ALSA support

**Comment by joshua-maros** [comment]
It looks like I did not correctly modify the installer after changing the linking, so some new files were not being installed. JACK now seems to work correctly when running a locally built installer on my system. I'll probably trigger another beta build later today which should automatically close this PR whenever it happens.
